### ISSUE TITLE
failed to execute script

### ISSUE THREAD

**Issue by vos6434** [zampierilucas/HeadseControl-SystemTray#4]
![image](https://user-images.githubusercontent.com/21976486/110698110-239e4180-81e5-11eb-9b35-357f296c6ea4.png)

**Comment by zampierilucas** [comment]
@vos6434 does any error message is shown after this one?

**Comment by vos6434** [comment]
No

**Comment by vos6434** [comment]
After the error, it just shows this icon in my tray.
![image](https://user-images.githubusercontent.com/21976486/110702882-feaccd00-81ea-11eb-866a-6846abbaf4f2.png)

**Comment by zampierilucas** [comment]
That's actually a pretty good tip, I have an idea of what might be causing it, can you try the latest build and see if it works for you? https://github.com/zampierilucas/HeadsetControl-SystemTray/releases/tag/latest

**Comment by vos6434** [comment]
same issue again

**Comment by Luddi96** [comment]
Hi,
Same issue here: Latest as well as 1.2 crash without error message
![image](https://user-images.githubusercontent.com/60077383/116727066-61009d80-a9e4-11eb-9696-d85b4744eb35.png)
I have a Arctis 9, Windows 10 N with MFP installed, German language pack
If I run headsetcontrol.exe from the bin folder, it says "No supported headset found"

**Comment by zampierilucas** [comment]
I've just spinned-up a fresh windows 10 21H1 machine and it works just fine,  even without running as administrator. 

@vos6434 @Luddi96 any chance that any you can clone the repository and run the HeadsetControl_SystemTray.py with python?

**Comment by vos6434** [comment]
I've switched to a new headset haha Using the Corsair Virtuoso now which provides a battery icon in the tray.

**Comment by Luddi96** [comment]
@vos6434 @zampierilucas Haha, exactly same for me. Switched to Virtuoso, which in my opinion is far superior to Steelseries.
