### ISSUE TITLE
Only showing disconnected

### ISSUE THREAD

**Issue by iamrm91** [zampierilucas/HeadseControl-SystemTray#5]
![headset_tray](https://user-images.githubusercontent.com/96551990/147162586-a5659c6d-7e9c-4c59-a9b5-d3d2e66339b6.png)

Headsetcontrol is installed and working for a Corsair Void Pro RGB but this system tray icon is only reporting headset disconnected. Did I miss some instructions for setup?

**Comment by zampierilucas** [comment]
Hey @iamrm91, It might've been an issue of using an older version of headsetcontrol internally. I've pushed a new build with the updated version 2.6 https://github.com/zampierilucas/HeadsetControl-SystemTray/releases/tag/latest
Also, If that doesn't work, can you sent the log file called `headsetcontrol.log`, on your temp path?

**Comment by elgarfo** [comment]
i had the same issue. your newer version fixed it for me. thank you

**Comment by zampierilucas** [comment]
Thanks for checking @elgarfo, closing this issue then.

**Comment by YorVeX** [comment]
Same story, the "Added missing dll" version didn't work, using the latest dev build fixed it and it's now running fine for my G933. Thanks for your work!

**Comment by zampierilucas** [comment]
@YorVeX thanks for the ping, I moved the latest development build to and official one, so others won't face the same issue you faced :D
