### ISSUE TITLE
Shows wrong battery percentage with Logitech G733 headset

### ISSUE THREAD

**Issue by Moonwrld** [zampierilucas/HeadseControl-SystemTray#6]
See attached images:
![image](https://user-images.githubusercontent.com/125472173/223414374-d09c5e63-6bb2-497f-b13b-87262cd368a8.png)
![image](https://user-images.githubusercontent.com/125472173/223414446-1b59f938-4c84-42fd-be1d-72abc3181613.png)

**Comment by zampierilucas** [comment]
Hi, can you verify if the output of [Sapd/HeadsetControl](https://github.com/Sapd/HeadsetControl) is also incorrect?

**Comment by Moonwrld** [comment]
![image](https://user-images.githubusercontent.com/125472173/223467091-a214879a-923f-4339-84ba-c7e2fe162bc7.png)
well, almost exactly right but doesn't state my model in those headsets listed

**Comment by zampierilucas** [comment]
Updated the HeadsetContro.exe to the latest version on https://github.com/zampierilucas/HeadsetControl-SystemTray/releases/tag/latest, can you check again?

**Comment by Moonwrld** [comment]
Still showing wrong percentage. 91% on headset controlsystem tray and 72% on the logitech g hub software

**Comment by zampierilucas** [comment]
My (limited) understanding of HeadsetControl is that it has a percentage curve based on the battery voltage of your headset, and it uses that to guess your battery percentage, as Logitech doesn't expose the direct percentage on an external API, which makes sense why you % is closer to the Logitech one while being almost full. I would suggest check the output of [HeadsetControl](https://github.com/Sapd/HeadsetControl) while on 50% battery or so, if it is still showing a bit discrepancy, it might mean that the curve on HeadsetControl needs to be adjusted for your headset model.
