### ISSUE TITLE
Arctis Nova 7 is only detected on 2.7

### ISSUE THREAD

**Issue by fibrasek** [zampierilucas/HeadseControl-SystemTray#7]
So I had to drop the 2.7 executable of HeadsetControl into the temp folder, and my headeset (Arctis Nova 7) got detected on the reload.

Is there any plans to bump it 2.7 on the next release?

**Comment by zampierilucas** [comment]
Sure, let me do that rn

**Comment by zampierilucas** [comment]
done  https://github.com/zampierilucas/HeadsetControl-SystemTray/releases/tag/latest

**Comment by fibrasek** [comment]
Awesome! Going to test it right now!
